trigger:
- main

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build
  displayName: 'Build'
  steps:
  - checkout: self

  - task: CopyFiles@2
    displayName: 'Copy HTML files'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '**/*.html'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

- job: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  condition: succeeded()
  steps:
  - task: AzureWebApp@1
    displayName: 'Azure Web App Deploy'
    inputs:
      azureSubscription: 'YourAzureServiceConnection'  # Reemplaza con tu conexión de servicio de Azure
      appName: 'yourwebapp'
      package: '$(System.DefaultWorkingDirectory)/drop/**/*.html'
