trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - task: CopyFiles@2
    displayName: 'Copy HTML files'
    inputs:
      command: 'ls'
      Contents: '**/*.html'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
