apiVersion: v1
kind: Pod
metadata:
 name: nuevopod
spec:
  containers:
  -  name: nginx1
     image: nginx:alpine
     env:
      - name: Mivariable
        value: "hola"
      - name: DD_AGENT_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
     resources:
      requests:
        memory: "20Mi"
        cpu: "10m"
      limits:
        memory: "20Mi"
        cpu: "20m"
     readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
     livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
     ports:
      - containerPort: 80
