name: ejemplo_pull_request
on:
    pull_request:
        types:
            - [opened, labeled]
        branches:
            - 'releases/**'
        paths:
            - '**.js'
jobs:
    ejecutando:
        runs-on: ubuntu-latest
        steps:
            - name: ejecutando
                run: echo ejecuando dentro de un pull request